config/routes.rb
Rails.application.routes.draw do
  resources :submissions, only: [ :index, :show ] do
    member do
      patch :approve
      patch :reject
      get :export
    end
  end
  resources :assignments
  resources :users
  root "worklogs#index"

  resources :companies do
    resources :projects, only: [ :index, :new, :create ]
  end

  resources :projects, except: [ :index, :new, :create ] do
    resources :rates
  end

  resources :worklogs do
    collection do
      get :export
      post :submit_timesheet
    end
  end
  resource :session, only: [ :new, :create, :destroy ]
  get "signin" => "sessions#new"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :worklogs, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :rates
  belongs_to :company

  has_many :users, through: :assignments, source: :user

  validates :name, :company_id, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_signin
  before_action :require_admin
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new(company_id: params[:company_id])
    @companies = Company.all
  end

  # GET /projects/1/edit
  def edit
    @companies = Company.all
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to companies_path, notice: "Project was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :name, :company_id ])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% url = project.new_record? && project.company ? company_projects_path(project.company) : project %>

<%= form_with(model: project, url: url, class: "contents") do |form| %>
  
  <% if project.errors.any? %>
    <div class="p-4 mb-4 bg-red-50 text-red-600 rounded-md border border-red-200">
      <h2 class="font-bold text-sm mb-2"><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul class="list-disc pl-5 text-sm">
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex items-center gap-4 mb-4">
    <%= form.label :name, class: "font-bold min-w-[120px]"  %>
    <%= form.text_field :name, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
  </div>

  <div class="flex items-center gap-4 mb-4">
    <% if project.company_id && project.new_record? %>
      <%= form.hidden_field :company_id %>
      
      <span class="font-bold min-w-[120px]">Company</span>
      <span class="text-gray-700 dark:bg-zinc-300 font-medium">
        <%= project.company.name %>
      </span>
    
    <% else %>
      <%= form.label :company_id, class: "font-bold min-w-[120px]" %>
      <%= form.collection_select :company_id, 
            Company.order(:name), :id, :name, 
            { prompt: "Select a Company" },
            { class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" } %>
    <% end %>
  </div>

  <div class="mt-4">
    <%= form.submit "Save Project", class: "button-success cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= link_to "#{project.company.name}", project.company, class: "underline" %>
  </p>
  <p>
    <strong>Assigned to:</strong>
    <% project.users.each do |user| %>
      <p class="underline"><%= link_to "#{user.first_name} #{user.last_name}", user %></p>
    <% end %>
  </p>

</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<div class="form-card">
  <h1  class="h1-style">Editing project</h1>
  <%= render "form", project: @project %>
  <div class="mt-4">
    <%= link_to "Show this project", @project, class: "button" %> |
    <%= back_button %>
  </div>
</div>

app/views/projects/index.html.erb
<% content_for :title, "Projects" %>

<div id="projects">
  <h1 class="h1-style form-card">Projects</h1>

  <% @projects.each do |project| %>
    <div class = "form-card">
      <%= render project %>
      <p class="mt-3">
        <%= link_to "View project", project, class: "button-secondary" %>
      </p>
    </div>
  <% end %>
  <div class="mt-6 form-card">
    <%= link_to "New project", new_project_path, class: "button-success" %>
  </div>
</div>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<div class="form-card">
  <h1  class="h1-style">New project</h1>
  <%= render "form", project: @project %>

  <div class="mt-4">
    <%= link_to companies_url, class: "button-secondary" do %>
      <%= icon_text("arrow-left", "Back to companies") %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="form-card">
  <h1  class="h1-style">Project card</h1>
  <%= render @project %>
  <div class="flex pt-6 gap-x-2">
    <%= link_to "Edit", edit_project_path(@project), class: "button" %>
    <%= link_to companies_url, class: "button-secondary" do %>
      <%= icon_text("arrow-left", "Back to companies") %>
    <% end %>
    <%= button_to "Delete project", @project, method: :delete, class: "button-danger" %>
</div>
</div>