config/routes.rb
Rails.application.routes.draw do
  resources :submissions, only: [ :index, :show ] do
    member do
      patch :approve
      patch :reject
      get :export
    end
  end
  resources :assignments
  resources :users
  root "worklogs#index"

  resources :companies do
    resources :projects, only: [ :index, :new, :create ]
  end

  resources :projects, except: [ :index, :new, :create ] do
    resources :rates
  end

  resources :worklogs do
    collection do
      get :export
      post :submit_timesheet
    end
  end
  resource :session, only: [ :new, :create, :destroy ]
  get "signin" => "sessions#new"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :projects

  def address_lines
    if address_line_1 && address_line_2
      "#{address_line_1}, #{address_line_2}".strip
    else
      "#{address_line_1}#{address_line_2}".strip
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_signin
  before_action :require_admin
  before_action :set_company, only: %i[ show edit update ]
  def index
    @companies = Company.includes(:projects)
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "Company details were successfully updated.", status: :see_other }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

private
    def set_company
      @company = Company.find(params.expect(:id))
    end

    def company_params
      params.expect(company: [ :name, :address_line_1, :address_line_2,
                               :postcode, :city, :country, :vat, :account_number,
                               :contact_phone, :contact_email, :contact_person ])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
    <% if company.errors.any? %>
        <div class="p-4 mb-4 bg-red-50 text-red-600 rounded-md border border-red-200">
            <h2 class="font-bold text-sm mb-2"><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>
        </div>
    <% end %>
    <div class="flex items-center gap-4 mb-4">
        <%= form.label :name, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :name, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :address_line_1, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :address_line_1, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :address_line_2, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :address_line_2, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :postcode, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :postcode, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :city, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :city, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :country, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :country, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :vat, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :vat, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :account_number, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :account_number, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :contact_phone, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :contact_phone, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :contact_email, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :contact_email, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>

    <div class="flex items-center gap-4 mb-4">
        <%= form.label :contact_person, class: "font-bold min-w-[120px]"  %>
        <%= form.text_field :contact_person, class: "rounded-sm border border-zinc-500 bg-white dark:bg-zinc-300 px-2 py-1" %>
    </div>
    <div class="flex gap-x-4">
        <% if company.new_record? %>
            <div>
                <%= form.submit "Create Company", class: "button-success cursor-pointer" %>
            </div>
        <% else %>
            <div>
                <%= form.submit "Update Company", class: "button-success cursor-pointer" %>
            </div>
        <% end %>
        <%= back_button %>
    </div>
<% end %>

app/views/companies/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Companies#create</h1>
  <p>Find me in app/views/companies/create.html.erb</p>
</div>

app/views/companies/edit.html.erb
<div class="form-card">
  <h1 class="font-bold text-4xl">Edit <%= @company.name %></h1>
  <div class="form-card">
    <%= render "form", company: @company %>
  </div>
</div>

app/views/companies/index.html.erb
<% content_for :title, "Companies" %>

<div class="w-full max-w-4xl mx-auto mt-6 px-4 form-card">
  <div class="flex items-center justify-between mb-6">
    <h1 class="text-3xl font-bold text-zinc-800">Companies</h1>
    <%= link_to "New Company", new_company_path, class: "button-success" if current_user_admin? %>
  </div>

  <div class="grid gap-6 md:grid-cols-2 ">
    <% @companies.each do |company| %>
      <div class="form-card hover:scale-[1.01] transition-transform duration-200">
        <div class="flex items-center justify-between mb-4">
          <h2 class="text-xl font-bold text-gray-900 dark:text-zinc-800">
            <%= company.name %>
          </h2>
          <span class="px-2 py-1 text-xs font-medium bg-indigo-100 text-indigo-800 rounded-md dark:bg-indigo-500/50 dark:text-white">
            <%= pluralize(company.projects.count, 'Project') %>
          </span>
        </div>

        <% if company.projects.any? %>
          <div class="space-y-2 mb-10">
            <p class="text-xs font-semibold text-gray-500 uppercase tracking-wider">Active Projects</p>
            <ul class="space-y-1">
              <% company.projects.each do |project| %>
                <li class="flex items-center gap-2 text-sm text-gray-700 dark:text-zinc-600">
                  <%= heroicon "folder", variant: :mini, options: { class: "w-4 h-4 text-gray-400" } %>
                  <%= link_to "#{project.name}", project, class: "underline" %>
                </li>
              <% end %>
            </ul>
          </div>
        <% else %>
          <p class="text-sm text-gray-500 italic">No active projects</p>
        <% end %>
        
        <div class="my-6 pt-4 border-t border-gray-700 flex justify-between items-center absolute bottom-0 divide-x divide-zinc-600">
   
          <%= link_to "Edit Company", edit_company_path(company), class: "text-sm text-indigo-500 hover:text-indigo-400 font-medium px-1" %>

          <%= link_to new_company_project_path(company_id: company.id), class: "flex items-center gap-1 text-sm text-green-600 hover:text-green-700 font-medium px-1" do %>
            <%= icon_text("plus", "Add Project")%>
          <% end %>

          <%= link_to company, class: "flex items-center gap-1 text-sm text-green-600 hover:text-green-700 font-medium px-1" do %>
            <%= icon_text("eye", "View")%>
          <% end %>

          <%= link_to company, class: "flex items-center gap-1 text-sm text-green-600 hover:text-green-700 font-medium px-1" do %>
            <%= icon_text("banknotes", "Accounting")%>
          <% end %>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/companies/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Companies#new</h1>
  <p>Find me in app/views/companies/new.html.erb</p>
</div>

app/views/companies/show.html.erb
<div class="form-card">
<h1 class="h1-style">Company card</h1>
  <div class="flex gap-x-6">
    <div class="form-card overflow-hidden shadow border">
        <div class="px-4 mb-6 sm:px-6">
            <h3 class="text-lg leading-6 font-medium text-zinc-900">
                Company profile
            </h3>
            <p class="mt-1 max-w-2xl text-sm text-zinc-500">
              Details used for invoicing and legal/business communications
            </p>

        </div>
        <div class="border-t border-zinc-200 px-4 py-5 sm:p-0">
            <dl class="sm:divide-y sm:divide-zinc-200 dark:divide-zinc-500">
              <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                  <dt class="text-sm font-medium text-zinc-500">
                      Company name
                  </dt>
                  <dd class="mt-1 text-sm text-zinc-900 sm:mt-0 sm:col-span-2">
                      <%= @company.name %>
                  </dd>
              </div>
              <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                  <dt class="text-sm font-medium text-zinc-500">
                      Contact email
                  </dt>
                  <dd class="mt-1 text-sm text-zinc-900 sm:mt-0 sm:col-span-2">
                      <%= @company.contact_email || "N/A" %>
                  </dd>
              </div>
              <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                  <dt class="text-sm font-medium text-zinc-500">
                      Contact phone
                  </dt>
                  <dd class="mt-1 text-sm text-zinc-900 sm:mt-0 sm:col-span-2">
                      <%= @company.contact_phone || "N/A" %>
                  </dd>
              </div>
              <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                  <dt class="text-sm font-medium text-zinc-500">
                      Address
                  </dt>
                  <dd class="mt-1 text-sm text-zinc-900 sm:mt-0 sm:col-span-2">
                      <%= @company.address_lines.present? ? @company.address_lines : "N/A" %><br>
                      <%= @company.city%>, <%= @company.country %> <%= @company.postcode %>
                  </dd>
              </div>
            </dl>
            <div>
              <%= link_to edit_company_path, class: "button-secondary" do %>
                <%= icon_text("pencil", "Edit") %>
              <% end %>
            </div>
        </div>
        
    </div>
    <div class="form-card">
      <h3 class="text-lg leading-6 font-medium text-gray-900">
                Projects
      </h3>
      <p class="mt-1 max-w-2xl text-sm text-gray-500">
        List of projects requested by the company
      </p>
      <table class="min-w-full divide-y divide-gray-200 mt-6 w-full">
          <thead>
              <tr>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-32 truncate">Name</th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Consultants</th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-24">Action</th>
              </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
              <% @company.projects.each do |project| %>
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="w-32 truncate">
                        <%= project.name %>
                      </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <% project.users.each do |user| %>
                        <p class="underline"><%= link_to "#{user.first_name} #{user.last_name}", user %></p>
                      <% end %>
                    </td>
                    <td class="px-4 py-2 whitespace-nowrap">
                      <div class="gap-x-2">
                        <%= button_to project_path(project),
                                      method: :get,
                                      class: "button mb-2" do %>
                          <%= icon_text("eye", "Show") %>
                        <% end %>
                        <%= button_to edit_project_path(project),
                                      method: :get,
                                      class: "button-secondary" do %>
                          <%= icon_text("pencil", "Edit") %>
                        <% end %>
                      </div>
                    </td>
                </tr>
              <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/companies/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Companies#update</h1>
  <p>Find me in app/views/companies/update.html.erb</p>
</div>