config/routes.rb
Rails.application.routes.draw do
  resources :submissions, only: [ :index, :show ] do
    member do
      patch :approve
      patch :reject
      get :export
    end
  end
  resources :assignments
  resources :users
  root "worklogs#index"

  resources :companies do
    resources :projects, only: [ :index, :new, :create ]
  end

  resources :projects, except: [ :index, :new, :create ] do
    resources :rates
  end

  resources :worklogs do
    collection do
      get :export
      post :submit_timesheet
    end
  end
  resource :session, only: [ :new, :create, :destroy ]
  get "signin" => "sessions#new"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/approved_work.rb
class ApprovedWork < ApplicationRecord
  belongs_to :submission
  belongs_to :project
  belongs_to :user
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :projects

  def address_lines
    if address_line_1 && address_line_2
      "#{address_line_1}, #{address_line_2}".strip
    else
      "#{address_line_1}#{address_line_2}".strip
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :worklogs, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :rates
  belongs_to :company

  has_many :users, through: :assignments, source: :user

  validates :name, :company_id, presence: true
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :user_id, uniqueness: { scope: :project_id, message: "Employee already has a rate for this project" }
  validates :inbound_rate, :outbound_rate, numericality: { greater_than_or_equal_to: 0 }
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  has_many :worklogs, dependent: :nullify

  enum :status, { draft: 0, approved: 1, rejected: 2 }

  validates :user_id, uniqueness: { scope: [ :period_start, :period_end, :id ] }

  def chart_data
    logs = worklogs.order(log_date: :asc)

    hours_by_date = logs.group(:log_date).sum(:hours)

    (period_start..period_end).each_with_object({}) do |date, hash|
      hash[date] = hours_by_date[date] || 0
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :worklogs, dependent: :destroy
  has_many :assignments, dependent: :destroy

  has_many :projects, through: :assignments, source: :project
  has_many :submissions, dependent: :destroy
  has_many :rates

  validates :first_name, :last_name, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
  validates :notification_email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8 }, allow_nil: true
  validate :password_complexity

  def full_name
    "#{first_name} #{last_name}".strip
  end


  private

  def password_complexity
    # skip validation if there is no password (on update)
    return if password.blank?

    # check for uppercase
    unless password.match?(/[A-Z]/)
      errors.add :password, "must include at least one uppercase letter"
    end

    # check for lowercase
    unless password.match?(/[a-z]/)
      errors.add :password, "must include at least one lowercase letter"
    end

    # check for digits
    unless password.match?(/[0-9]/)
      errors.add :password, "must include at least one digit"
    end

    # check for special characters
    # crutch to avoid whitelist: this regex looks for anything that is NOT a letter or number
    unless password.match?(/[^a-zA-Z0-9]/)
      errors.add :password, "must include at least one special character"
    end
  end
end

app/models/worklog.rb
class Worklog < ApplicationRecord

  belongs_to :project
  belongs_to :user
  belongs_to :submission, optional: true

  validates :hours, presence: true, numericality: { greater_than: 0 }

  validates :note, length: { minimum: 6 }

  validates :log_date, presence: true

  scope :not_submitted, -> { where(submission_id: nil) }

  scope :for_period, ->(start_date, end_date) {
    where(log_date: start_date..end_date)
  }

  def editable?
    submission_id.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def nav_link(text, path)
    active = current_page?(path)

    classes = "px-4 hover:text-white transition duration-200 "

    classes += active ? "font-bold text-white underline decoration-2 underline-offset-4" : "text-white/80"

    content_tag(:li, class: classes) do
      link_to text, path
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/button_helper.rb
module ButtonHelper
  def icon_text(icon, text, icon_options: {})
    default_options = { variant: :solid, options: { class: "w-4 h-4" } }

    final_options = default_options.deep_merge(icon_options)

    tag.span(class: "flex items-center gap-1") do
      concat heroicon(icon, **final_options)
      concat tag.span(text)
    end
  end

  def new_worklog_button
    link_to new_worklog_path, class: "button-success" do
      icon_text("pencil-square", "New Worklog")
    end
  end

  def login_button
    button_tag(type: "submit", class: "button-success") do
      icon_text("arrow-right-on-rectangle", "Sign In")
    end
  end

  def filter_button
    button_tag(type: "submit", class: "button") do
      icon_text("funnel", "Filter")
    end
  end

  def back_button(path = :back)
    link_to path, class: "button-secondary" do
      icon_text("arrow-left", "Back")
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/worklogs_helper.rb
module WorklogsHelper
end

app/views/layouts/_alert.html.erb
<% if notice.present? %>
  <div class="form-card bg-green-50 border-green-500 text-green-700 dark:bg-teal-700/50 dark:text-zinc-100">
    <%= notice %>
  </div>
<% end %>

<% if alert.present? %>
  <div class="form-card bg-red-50 border-red-500 text-red-700 dark:bg-red-900/50 dark:text-zinc-100">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div data-controller="toast"
       class="fixed top-5 right-5 z-50 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow-lg dark:text-gray-800 dark:bg-zinc-400 border border-gray-100 dark:border-zinc-700 transform transition-all duration-500 translate-x-0 opacity-100">
    
    <% if type == "notice" %>
      <div class="inline-flex items-center justify-center shrink-0 w-8 h-8 bg-green-200 border-green-500 text-green-700 dark:bg-teal-500/70 dark:text-zinc-100 rounded-lg">
        <%= heroicon "check", variant: :solid, options: { class: "w-5 h-5" } %>    </button>
      </div>
    <% else %>
       <div class="inline-flex items-center justify-center shrink-0 w-8 h-8 bg-red-50 border-red-500 text-red-700 dark:bg-red-500/70 dark:text-zinc-100 rounded-lg">
        <%= heroicon "exclamation-triangle", variant: :solid, options: { class: "w-5 h-5" } %>    </button>
      </div>
    <% end %>

    <div class="ml-3 text-sm font-normal"><%= message %></div>
    
    <button type="button" data-action="toast#close" class="ml-auto -mx-1.5 -my-1.5 bg-zinc-300 text-gray-600 hover:text-gray-700 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-800 dark:hover:text-white dark:bg-zinc-500 dark:hover:bg-zinc-700">
        <%= heroicon "x-mark", variant: :solid, options: { class: "w-5 h-5" } %>    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-auto bg-white/50 backdrop-blur-md py-3 flex">
    <% if current_user %>
        <div class="text-zinc-900 ml-3">
            Made by 
            <a href="https://github.com/OleksiiLapshov" class="underline">Tachyon_Shift</a>
        </div>
    <% end %>
    <div data-controller="theme" class="justify-end ml-auto pr-3">
        <button 
            data-action="click->theme#toggle" 
            class="p-1 rounded-lg bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors shadow-2xl drop-shadow-2xl">
            
            <span class="font-bold flex">
                <%= heroicon "sun", variant: :solid, options: { class: "w-4 h-4" } %>
                <%= heroicon "arrows-up-down", variant: :solid, options: { class: "w-4 h-4" } %>
                <%= heroicon "moon", variant: :solid, options: { class: "w-4 h-4" } %>
            </span>
            
        </button>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="sticky top-0 z-50 w-full bg-gradient-to-r from-orange-400 to-orange-500 dark:from-slate-950 dark:to-slate-900 border-b border-white/10 shadow-md">
    
    <div class="mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        
        <div class="shrink-0">
        <%= link_to root_path, class: "flex items-center gap-3 group" do %>
            
            <%= image_tag "cozy-cat.png", 
                alt: "Work-Log", 
                class: "h-8 w-auto block dark:hidden transition-transform group-hover:scale-105" %>

            <%= image_tag "dark-cat.png", 
                alt: "Work-Log", 
                class: "h-8 w-auto hidden dark:block transition-transform group-hover:scale-105" %>

            <span class="font-bold text-xl text-white dark:text-zinc-200">
            Work-Log
            </span>
        <% end %>
        </div>

        <ul class="flex flex-wrap items-center justify-end gap-x-2 text-m font-medium text-white dark:text-zinc-300">
          
          <% if current_user %>
            <div class="flex items-center divide-x divide-white/30">
                <%= nav_link "Home", root_path %>
                <%= nav_link "Timesheets", submissions_path %>
                <%= nav_link "Worklogs", worklogs_path %>
                
                <% if current_user_admin? %>
                    <%#= nav_link "Projects", projects_path %>
                    <%= nav_link "Companies", companies_path %>
                    <%= nav_link "Users", users_path %>
                <% end %>
            </div>

            <li class="ml-6">
              <%= link_to user_path(current_user), class: "underline decoration-orange-300 underline-offset-4 hover:decoration-white transition" do %>
                <%= icon_text("user-circle", current_user.first_name) %>
              <% end %>
            </li>
            
            <li class="ml-4">
              <%= link_to session_path,
                          data: { turbo_method: :delete },
                          class: "button bg-white/10 hover:bg-white/20 border-none text-white" do %>
                <%= icon_text("arrow-left-on-rectangle", "Sign Out") %>
              <% end %>
            </li>

          <% else %>
            <% if current_user %>
              <li>
                <%= link_to "Sign In", signin_path, class: "button-secondary" %>
              </li>
            <% end %>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Loggy Lou" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-screen bg-gradient-to-b from-[#f8e9ca] to-[#d9a673] bg-fixed dark:from-blue-950 dark:to-indigo-950">
    <%= render "layouts/header" %>
    <div id="flash-messages">
      <%= render "layouts/flash" %>
    </div>
    <%# TODO: make this work when JS is disabled and Stimulus is unavailable (it works, but need general solution) %>
    <%#= render "layouts/alert" %>
    <%= yield %>
    <br>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_worklogs_table.html.erb
<div class="form-card">
    <table class="table-fixed w-full border border-zinc-500 border-collapse">
    <thead class="text-lf font-bold">
      <tr class="bg-zinc-200">
        <th class="border border-zinc-500 py-2 px-3 w-32">Date</th>
        <% if current_user_admin? %>
            <th class="border border-zinc-500 py-2 px-3 w-32">Employee</th>
        <% end %>
        <th class="border border-zinc-500 py-2 px-3 w-18">Hours</th>
        <th class="border border-zinc-500 py-2 px-3 w-48">Project</th>
        <th class="border border-zinc-500 py-2 px-3">Notes</th>
        <% if !current_user_admin? %>
            <th class="border border-zinc-500 py-2 px-3 w-48">Actions</th>
        <% end %>
      </tr>
    </thead>
      <tbody>
        <% worklogs.each do |worklog| %>
          <tr>
            <td class="border border-zinc-500 py-2 px-3"><%= worklog.log_date%></td>
            <% if current_user_admin? %>
                <td class="border border-zinc-500 py-2 px-3"><%= "#{worklog.user.full_name}" %></td>
            
            <% end %>
            <td class="border border-zinc-500 py-2 px-3"><%= worklog.hours %></td>
            <td class="border border-zinc-500 py-2 px-3"><%= worklog.project.name %></td>
            <td class="border border-zinc-500 py-2 px-3 truncate" title="<%= worklog.note %>"><%= worklog.note %></td>
            <% if !current_user_admin? %>
                <td class="border border-zinc-500 py-2 px-2">
                <div class="flex gap-2 justify-center">
                    <%= button_to worklog,
                                params: { month: params[:month], year: params[:year] }.compact_blank,
                                method: :get,
                                class: "button-secondary" do%>
                      <%= icon_text("eye", "View") %>
                    <% end %>
                    <%= button_to edit_worklog_path(worklog),
                                method: :get,
                                class: worklog.editable? ? "button" : "button-disabled", 
                                disabled: !worklog.editable? do %>
                      <%= icon_text("pencil", "Edit") %>
                    <% end %>
                </div>
                </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>